### ISSUE TITLE
V3 migration guide, breaking changes to KeycloakProvider, useKeycloak, initConfig

### ISSUE THREAD

**Issue by stahlmanDesign** [react-keycloak/react-keycloak#101]
V3 has a lot of breaking changes. The examples ARE up to date (thank you), but since I didn't see a migration guide yet I wanted to share the changes I made to get v3 working:

# imports
v2.x | v3
---------- | ------------ 
import { KeycloakProvider } from '@react-keycloak/web' | import { ReactKeycloakProvider } from '@react-keycloak/web'
withKeycloak | removed?, can use useKeycloak() instead
const [keycloak, initialized] = useKeycloak() | const **{** keycloak, initialized **}** = useKeycloak()

# Provider params
v2.x | v3
----------|------------ 
initConfig | initOptions
keycloak | authClient={ keycloak }

**Comment by panz3r** [comment]
Hi @stahlmanDesign ,

Thanks for your feedback and for the contribution, I was writing the migration guide but had not yet published it.

I'll publish something as soon as possible.
