### ISSUE TITLE
Login form as a react component

### ISSUE THREAD

**Issue by hmbrg** [react-keycloak/react-keycloak#102]
**Is your feature request related to a problem? Please describe.**
How can I create a hovering modal form as a React Component that asks the user to enter username and password? All that without redirecting to Keycloaks login URL.

**Describe the solution you'd like**
Logging in a user using a login form directly rendered in the React SPA.

**Describe alternatives you've considered**
Maybe not using Keycloak at all, because this might be considered an anti-pattern. Is it?

**Additional context**
None.

**Comment by panz3r** [comment]
Hi @hmbrg ,

Unfortunately that is not possible using keycloak-js adapter (and so using react-keycloak).

If you want to implement something like that but keep Keycloak to manage the users you can try to implement a wrapper API around the Keycloak Admin SDK.

Hope this helps you.

**Comment by hmbrg** [comment]
Thanks for your answer! Is there any widely available library that can to that?

**Comment by panz3r** [comment]
you can have a look at [keycloak-nodejs-admin-client](https://github.com/keycloak/keycloak-nodejs-admin-client)

**Comment by Doc999tor** [comment]
Hey @panz3r, I'm working on React app with authentication management by KeyCloak
As far as I understand I can't manage logging in/registration via REST API?
Getting the credentials from user in a regular react component and checking it against KeyCloak server?
