### ISSUE TITLE
error with typescript in version 3.0.

### ISSUE THREAD

**Issue by Donatien26** [react-keycloak/react-keycloak#103]
**Describe the bug**
When i use @react-keycloak/web with a typescript project i have this error
```
..../node_modules/@react-keycloak/web/lib/useKeycloak.d.ts
TypeScript error in .../node_modules/@react-keycloak/web/lib/useKeycloak.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type {AuthClient} from '@react-keycloak/core';
      |             
    2 | export declare type useKeycloakHookResults<T extends AuthClient> = {
    3 |     initialized: boolean;
    4 |     keycloak?: T;
```

**Desktop (please complete the following information):**

- OS: Windows
- Browser all

**Additional context**
this bug was not present on version 2.1.1

**Comment by Donatien26** [comment]
It seems to be resolve when i modify useKeycloak.d.ts like this :
```js
 import AuthClient from '@react-keycloak/core';
          
export declare type useKeycloakHookResults<T extends AuthClient> = {
             initialized: boolean;
             keycloak?: T;
```
But i don't know if it's what we want

**Comment by panz3r** [comment]
Hi @Donatien26 ,

To fix TS error `TS1005` you should upgrade `typescript` dependency to a version which supports `import type` syntax (so version `3.8` or later - by default `create-react-app` TS template specifies `3.6`).

**Comment by lubarskyy** [comment]
@panz3r I think it might be a good idea to reflect that using the `peerDependencies` - https://nodejs.org/es/blog/npm/peer-dependencies/#the-solution-peer-dependencies

**Comment by panz3r** [comment]
Hi @lubarskyy ,

> I think it might be a good idea to reflect that using the peerDependencies

I thought about that but I don't think that would be the ideal solution because that would imply that `react-keycloak` requires Typescript in order to work (and that's not the case) and would force users of the module to install it even if they won't use it (otherwise `npm` would complain with a warning each times the dependencies are installed).

Think for example a project bootstrapped with `create-react-app` but using pure JS, `react-keycloak` will still work in that case but by setting a `peerDependency` a warning will be thrown and the user would be forced to install `typescript`.

**Comment by Donatien26** [comment]
Ok thanks. But when i upgrade to typescript 3.8 or higher, the following code is not running : 
```js
  const { keycloak, initialized } = useKeycloak();
  const [userInfo, setUserInfo] = useState<any>(null);
  useEffect(() => {
    if (initialized) {
      keycloak.loadUserInfo().then((resp: any) => setUserInfo(resp));
    }
  }, [keycloak, initialized]);
```
typescript say that keycloak may be null so i add "if (initialized && keycloak)" but then typescript launch an error because loadUserInfo doesn't exist on keycloak which is detected an AuthClient. I've bypass the problem by casting as keycloak as an any object but i'm not convinced

**Comment by panz3r** [comment]
Hi @Donatien26 ,

> typescript say that keycloak may be null so i add "if (initialized && keycloak)"

This is true, there's a small change that the hook could be executed before the keycloak instance is set on the Provider, so the `keycloak` instance returned by `useKeycloak` might be null.

>  typescript launch an error because loadUserInfo doesn't exist on keycloak which is detected as AuthClient

to overcome this issue the `useKeycloak` hook allow specifying the type of the `keycloak` instance returned, like this 

```ts
const { keycloak, initialized } = useKeycloak<KeycloakInstance>(); 
```

**Note:** `KeycloakInstance` is a type that should be imported from `keycloak-js`.

> I've bypass the problem by casting keycloak as an any object but i'm not convinced

After specifying the return type this won't be necessary anymore.

Hope this helps you.

**Comment by Donatien26** [comment]
Thanks a lot , sorry for the inconvenience. I think we can close the issue. 👍

**Comment by lubarskyy** [comment]
> I thought about that but I don't think that would be the ideal solution because that would imply that `react-keycloak` requires Typescript in order to work (and that's not the case) and would force users of the module to install it even if they won't use it (otherwise `npm` would complain with a warning each times the dependencies are installed).
> 
> Think for example a project bootstrapped with `create-react-app` but using pure JS, `react-keycloak` will still work in that case but by setting a `peerDependency` a warning will be thrown and the user would be forced to install `typescript`.

I totally forgot about the need of supporting pure JS code bases :see_no_evil:. Nevertheless, I stumbled upon great example that might help in this scenario - https://github.com/mui-org/material-ui/pull/17211/files. You could specify that the certain peer dependency is optional and suppress any unnecessary warnings.

yarn RFC -https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md, also already supported in npm.

```json
  "peerDependencies": {
    "@types/react": "^16.8.6",
  },
  "peerDependenciesMeta": {
    "@types/react": {
      "optional": true
    }
  }
```

**Comment by panz3r** [comment]
Hi @lubarskyy ,

Thanks for the suggestion, I'll have a look at that 👍

**Comment by panz3r** [comment]
Added `typescript` as `optionalPeerDependency` on
 - `@react-keycloak/ssr@3.0.2`
 - `@react-keycloak/web@3.1.1`
