### ISSUE TITLE
Continuous Integration and Continuous Delivery Pipeline setup

### ISSUE THREAD

**Issue by karuppiah7890** [react-keycloak/react-keycloak#105]
**Is your feature request related to a problem? Please describe.**
I noticed that the repo has tests, but there is no automated Continuous Integration pipeline setup for the master branches or even PRs. I'm assuming there's no Continuous Delivery setup too.

**Describe the solution you'd like**
Add a CI/CD setup

**Comment by panz3r** [comment]
Hi @karuppiah7890 ,

Thanks for your feedback.

An initial setup of a CI pipeline has been implemented using GitHub Actions, I plan to add a full CD pipeline later on.

**Comment by karuppiah7890** [comment]
Awesome!!!
