### ISSUE TITLE
step1.html 404 Not found

### ISSUE THREAD

**Issue by sakenalimbayev** [react-keycloak/react-keycloak#107]
**Describe the bug**
Keycloak configured in Amazone EC2 instance, up and running successfully.
I'm creating simple React application and wanted to add Login page from Keycloak.
I followed example in your repository, but my screen is stucked with "Loading..." message.
In network I see that step1.html returned 404 Not Found.

**To Reproduce**

1. Follow the example provided in separate repository
2. Start app

**Screenshots**
https://paste.pics/05f3fb49911a1ec5c824b0372fc23ee3

**Comment by sakenalimbayev** [comment]
Update:
I tried to call directly from code keycloak.login(); and successfully redirected to login page, but without any CSS (strange...)
But after successful login, I'm redirecting back to my application, and I see that keycloack.authenticated property is still false.
Why?

**Comment by panz3r** [comment]
Hi @sakenalimbayev ,

The reported issue seems related to the version of `keycloak-js` and `keycloak` server you are using, the `step1.html` page is used to check for 3rd-party cookies support starting from `keycloak` `v11`, so should check that Keycloak server is at least version `11.0.0` if you are using `keycloak-js` `v11` or later.

**Comment by sakenalimbayev** [comment]
thank you @panz3r 
Issue resolved.
