### ISSUE TITLE
Wrong return type when using useKeycloak hook v3 and Typescript

### ISSUE THREAD

**Issue by leandrocrs** [react-keycloak/react-keycloak#109]
**Describe the bug**
`useKeycloak` is returning an `AuthClient` instance instead of `KeycloakInstance`.

AuthClient is a private type, not exported, and doesn't have properties like `authenticated`.

**To Reproduce**

1. Install `@react-keycloak/web@^3.0.0` in a react typescript enabled project
2. Try the following snippet:
```typescript
import { useKeycloak } from '@react-keycloak/web';
import React from 'react';
import { Redirect, Route, RouteProps } from 'react-router-dom';

export type ProtectedRouteProps = RouteProps;

export default function ProtectedRoute({ children, ...rest }: ProtectedRouteProps) {
	const { keycloak } = useKeycloak();

	console.log('ProtectedRoute: keycloak.initialized ', keycloak?.authenticated); // here is the problem

	return (
		<Route {...rest}>
			{keycloak?.authenticated ? (
				children
			) : (
				<Redirect
					to={{
						pathname: '/',
					}}
				/>
			)}
		</Route>
	);
}
```

**Expected behavior**
Get a `KeycloakInstance` instead `AuthClient` when using `useKeycloak()` hook.

**Screenshots**
How is work now:
<img width="1133" alt="Screen Shot 2020-10-15 at 16 35 35" src="https://user-images.githubusercontent.com/1456009/96179368-254e2c80-0f07-11eb-8894-ece260582d36.png">

My workaround for now:
<img width="1167" alt="Screen Shot 2020-10-15 at 16 35 51" src="https://user-images.githubusercontent.com/1456009/96179396-3008c180-0f07-11eb-8d71-0d64ba39e9fe.png">

**Comment by panz3r** [comment]
Hi @leandrocrs ,

Thanks for your feedback, the fix for this issue has been released to `npm` as `@react-keycloak/web` version `3.1.0`.
