### ISSUE TITLE
Documentation says initConfig instead of initOptions

### ISSUE THREAD

**Issue by Powersource** [react-keycloak/react-keycloak#112]
Here https://github.com/react-keycloak/react-keycloak/blob/master/packages/web/README.md#setup-keycloakprovider it says to use the prop `initConfig` but the one you should actually use is `initOptions` which you can see here https://github.com/react-keycloak/react-keycloak/blob/master/packages/core/src/provider.tsx#L130 (and which I've verified by testing)

**Comment by panz3r** [comment]
Fixed with PR #113
