### ISSUE TITLE
Authenticated on server side render but not on initial client side render (react-keycloak-examples/nextjs-app)

### ISSUE THREAD

**Issue by gustavlrsn** [react-keycloak/react-keycloak#115]
**Describe the bug**

I'm getting this error when running the [nextjs example app](https://github.com/react-keycloak/react-keycloak-examples/tree/master/examples/nextjs-app):

```
Warning: Text content did not match. Server: "My Account" Client: "Signup"
    in button (at Header.tsx:49)
    in header (at Header.tsx:10)
    in Header (at Layout.tsx:26)
    in div (at Layout.tsx:15)
    in Layout (at profile.tsx:48)
    in ProfilePage (at _app.tsx:33)
    in KeycloakProvider (created by SSRKeycloakProvider)
    in SSRKeycloakProvider (at _app.tsx:29)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

It seems like it is authenticated on the initial server side render, but then the initial client side render shows that I am not authenticated, until it rerenders to also become authenticated there.

**To Reproduce**

1. Run the [react-keycloak/next.js example](https://github.com/react-keycloak/react-keycloak-examples/tree/master/examples/nextjs-app)
2. Log in
3. Refresh the page

**Expected behavior**

Being logged in on both server and client

**Comment by lee-reinhardt** [comment]
This was briefly discussed over in the examples repo: https://github.com/react-keycloak/react-keycloak-examples/issues/11

**Comment by panz3r** [comment]
See the linked issue for more details

[react-keycloak/react-keycloak-examples#11](https://github.com/react-keycloak/react-keycloak-examples/issues/11)
