### ISSUE TITLE
Razzle persistor.getTokens is not a function

### ISSUE THREAD

**Issue by SimonHylander** [react-keycloak/react-keycloak#117]
**Describe the bug**
I've tried to setup a fresh razzle project following the [README](https://github.com/react-keycloak/react-keycloak/blob/master/README.md) example, however it seems that the Cookies object do not contain any properties if I print it. 

**To Reproduce**
1. git clone https://github.com/SimonHylander/keycloak-ssr.git
2. `$ yarn start`

**Expected behavior**
I expect to be able to log into my keycloak instance

**Screenshots**

![image](https://user-images.githubusercontent.com/8668801/96998390-ab83f780-1533-11eb-873d-b15dfdbd7769.png)

![image](https://user-images.githubusercontent.com/8668801/96998439-bf2f5e00-1533-11eb-8c7e-d7bb0ad05f12.png)

![image](https://user-images.githubusercontent.com/8668801/96998483-d0786a80-1533-11eb-9c7f-fbcaf5e190cf.png)

**Desktop (please complete the following information):**

- OS: Pop!_OS 19.10
- Browser: chrome
- Version 86.0.4240.75

**Comment by MikeyAlmighty** [comment]
@SimonHylander Need to wrap it with `SSRCookies` from `import { SSRCookies } from '@react-keycloak/ssr';`
If you're using version `3.x.x`:

And then in the `SSRKeycloakProvider`:
```
  <SSRKeycloakProvider
    keycloakConfig={keycloakCfg}
    persistor={SSRCookies(cookies)}
  >
```
