### ISSUE TITLE
Type checking doesn't work with Typescript < 4

### ISSUE THREAD

**Issue by DorianMaliszewski** [react-keycloak/react-keycloak#118]
Hi,

Just start a project (1 month) with React and your library. I always have problems with 
`import type {Keycloak} from "keycloak.js";`

I used the official create-react-app documentation to add typescript in the project and needed to upgrade my typescript version to ^4.0.2 (it was ~3.7.2) like you to make the library work fine.

Don't know if it's easy to make it work with both typescript version but I wanted to tell you that issue. Some users can have the same problem and will don't know how to solve it.

BTW, Thanks for this package :sweat_smile:

**Comment by panz3r** [comment]
Hi @DorianMaliszewski ,

Thanks for your feedback

> Just start a project (1 month) with React and your library. I always have problems with
> import type {Keycloak} from "keycloak.js";
>
> I used the official create-react-app documentation to add typescript in the project and needed to upgrade my typescript version to ^4.0.2 (it was ~3.7.2) like you to make the library work fine.

This issue has been discussed as part of issue #103 , the main issue here is that the `import type` syntax requires a Typescript version of at least `3.8` whilst `create-react-app` v3 specifies `~3.7.2` (as you reported), to fix this new versions of `@react-keycloak` packages now specify an `optionalPeerDependency` on `typescript` `>=3.8`.

> Don't know if it's easy to make it work with both typescript version but I wanted to tell you that issue. Some users can have the same problem and will don't know how to solve it.

This might be not longer an issue with the release of `create-react-app` v4 which upgraded the required version of `typescript` to `v4.x` (see official changelog here [facebook/create-react-app#v4.0.0](https://github.com/facebook/create-react-app/releases/tag/v4.0.0)) along with updated project templates.

> BTW, Thanks for this package

Hoping this module is helping you, Thank you for your feedback and for using this package 👍
