### ISSUE TITLE
initialized is always false, Also authenticated is always false after login

### ISSUE THREAD

**Issue by aabanaag** [react-keycloak/react-keycloak#119]
**Describe the bug**
I somehow followed the examples but the initialized value is still false, Also onEvent and onTokens doesn't work.

```
index.js
ReactDOM.render(
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <ThemeProvider theme={theme}>
        <ReactKeycloakProvider
          authClient={keycloak}
          onEvent={eventLogger}
          onTokens={tokenLogger}
        >
          <App />
        </ReactKeycloakProvider>
      </ThemeProvider>
    </ConnectedRouter>
  </Provider>,
  document.getElementById('root')
);

app.js
const App = () => {
  const dispatch = useDispatch();
  const isResourcePending = useSelector(selectResourcesPending);
  const { initialized } = useKeycloak();

  useEffect(() => {
    dispatch(fetchConfig());
  });

  console.log('INITIALIZED', initialized);
  if (isResourcePending || !initialized) {
    return <CircularProgress />;
  }

  return (
    <Suspense fallback={<CircularProgress />}>
      <Redirect from="/" to="/login" />
      <PrivateRoute path="/home" component={Home} />
      <Route path="/login" component={Login} />
    </Suspense>
  );
};
```

**To Reproduce**

**Expected behavior**
The value should be true.

**Screenshots**
![Screen Shot 2020-11-04 at 3 35 16 PM](https://user-images.githubusercontent.com/2245822/98082253-6193fd80-1eb3-11eb-8f0a-8b68c2dfb93e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thudaohd** [comment]
I have same issue

**Comment by shuklajay117** [comment]
I am also facing the same issue.

**Comment by panz3r** [comment]
Hi @aabanaag , @thudaohd , @shuklajay117 ,

Thanks for your feedbacks.

I tried to reproduce this issue using the `react-router` sample code from [react-keycloak/react-keycloak-examples](https://github.com/react-keycloak/react-keycloak-examples) and couldn't, everything worked as expected.

<img width="744" alt="RKC_working" src="https://user-images.githubusercontent.com/1754457/98465489-9bbe1180-21c9-11eb-9f03-4ee1bd748ba8.png">

Can you please provide more information about your environment?

>Desktop (please complete the following information):
>
>OS: [e.g. Windows/Mac]
>Browser [e.g. Chrome, Safari]
>Browser Version [e.g. 14.0.1]
>Keycloak server version [e.g. 11.0.2]
>`@react-keycloak/web` version [e.g. 3.4.0]

**Comment by aabanaag** [comment]
I used the latest version of react-keycloak, latest version of CRA. I'll create a sample project this week to show the issue.

**Comment by hmbrg** [comment]
This happens for me only in firefox!

**Comment by iocampomx** [comment]
Same issue here, I'm using these instructions: https://www.npmjs.com/package/@react-keycloak/web

![image](https://user-images.githubusercontent.com/5959795/99336704-4a9bc680-2836-11eb-885e-501efde224af.png)

Here an example of how I'm using it.

Every time I navigate to each route, Keycloak JS is reaching out the Keycloak server to get a new access token, somehow isn't persisting the information...

**Comment by 13474076037** [comment]
i have the same question, and i see somebody solve this by keycloak.init(), but i don't understand the principle. 
 https://www.javaroad.cn/questions/77455

**Comment by MacgyverMartins** [comment]
Same error here. Please open this issue again

**Comment by Ketler13** [comment]
The error still happens for me using next.js
