### ISSUE TITLE
Refreshing Page (Cmd + F5): Redirected to Keycloak Login Page

### ISSUE THREAD

**Issue by FelixMohr** [react-keycloak/react-keycloak#121]
**Describe the bug**
I have configured my app to be secured with *react-keycloak*. It works nicely, if I am not authenticated, I am redirected to the login page of Keycloak. After signing in, I can use the app.

However, if I refresh the page, I am again redirected to the login page. My code does not delete the auth information on refresh or something like that.

**To Reproduce**
```typescript
ReactDOM.render(
  <ApolloProvider client={apolloClient}>
    <I18nextProvider i18n={i18next}>
      <ThemeProvider>
        <ReactKeycloakProvider
          authClient={keycloak}
          onTokens={(tokens: AuthClientTokens) =>
            setTokens(tokens.token ?? '', tokens.idToken ?? '', tokens.refreshToken ?? '')
          }
          initOptions={{ onLoad: 'login-required' }}
        >
```
```typescript
import Keycloak from 'keycloak-js'
import { environment } from '../../constants/environment'

//keycloak init options
export const KEYCLOAK_INIT_OPTIONS = {
  url: environment.REACT_APP_LOGIN_URL,
  realm: environment.REACT_APP_LOGIN_REALM,
  clientId: 'login',
}

export const keycloak = Keycloak(KEYCLOAK_INIT_OPTIONS)
```

**Expected behavior**
If I refresh the page, I don't have to login again.

Am I missing something?

Thank you!

**Comment by FelixMohr** [comment]
It works if I put the tokens into storage, write a method ``getTokens`` for retrieving them and adapt the code as follows:

```typescript
const [token, refreshToken] = getTokens()
ReactDOM.render(
  <ApolloProvider client={apolloClient}>
    <I18nextProvider i18n={i18next}>
      <ThemeProvider>
        <ReactKeycloakProvider
          authClient={keycloak}
          onTokens={(tokens: AuthClientTokens) =>
            setTokens(tokens.token ?? '', tokens.idToken ?? '', tokens.refreshToken ?? '')
          }
          initOptions={{ onLoad: 'login-required', token, refreshToken }}
        >
...
```

**Comment by youjeongsue** [comment]
Hi, @FelixMohr ! Thank you for such a good example.
But could you also provide detailed implementations of the getTokens() and setTokens() functions?
I used **useState**, but it occurs infinite refresh token TT
It would be great if anyone can help.
