### ISSUE TITLE
How I can use keycloak instance in getServerSideProps(next.js)

### ISSUE THREAD

**Issue by oggy-kim** [react-keycloak/react-keycloak#126]
I declared SSRKeycloakProvider in _app.tsx. And it works well in every components.
```
export default function App({ Component, pageProps, cookies }: AppProps & InitialProps) {
  return (
    <SSRKeycloakProvider keycloakConfig={keycloakCfg} persistor={SSRCookies(cookies)}>
        <Component {...pageProps} />
    </SSRKeycloakProvider>
  );
}
```
I want to use some information(ex. email) in order to get states in component(like page/index.tsx). But I cannot use useKeycloak hook, because it's always used on top function. So, how's the solution to get information in getServerSideProps in next.js?

**Comment by MikeyAlmighty** [comment]
@oggy-kim

**Comment by oggy-kim** [comment]
@MikeyAlmighty Thanks your advice. I tried that. but error occured.
```
TypeError: Cannot read property 'getTokens' of undefined
```
and getKeycloakInstance() <- it needs at least 1 argument(keycloakCfg). I added that cfg, but it also make error.

**Comment by oggy-kim** [comment]
I found a answer. It cannot work on server-side.
[https://github.com/react-keycloak/react-keycloak/issues/84#issuecomment-667699580](url)

**Comment by oggy-kim** [comment]
@filippomc Thanks for your replay. That instance is StubInstance, not a real keycloakInstance. 
next.js check server-side first, and keycloak instance is only run on window env(not node.js).

**Comment by filippomc** [comment]
Thanks @oggy-kim you're totally right. I thought at start I could do something with the token but the token is not meaningful until the client side logic is called. Wonder the library is even using the keycloak-js and not the node api to implement proper server side logic.
