### ISSUE TITLE
Support for scopes

### ISSUE THREAD

**Issue by refucktor** [react-keycloak/react-keycloak#127]
First of all, thanks for your work and the effort to produce it.

I have tried in several ways to configure the way to set "**scopes**" to execute the authentication, I already checked your implementation but I cannot find any configuration available which allows me to set that parameter.

Is there any workaround for it? if no, are you planning to enhance the library with it?

Thanks a lot again!

**Comment by panz3r** [comment]
Hi @refucktor ,

The way to achieve what you need to is the following:
- set `initOptions` to have `{ onLoad: 'check-sso' }`
- when you need to authenticated your user call the `login` method from the `keycloak` instance returned by `useKeycloak` and pass the `scope` options as per `keycloak-js` documentation [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#login-options)

In case you need to set the `onLoad` option to `login-required` instead, unfortunately `keycloak-js` (which is used internally by `react-keycloak`) does not provide the ability to specify `scopes`.

Let me know if this helps you.

**Comment by SrMouraSilva** [comment]
Hello, @panz3r. I need to define a scope and I need to use `initOptions={{onLoad: 'login-required'}}` instead of `{ onLoad: 'check-sso' }`.

I think that `loginOptions` would be cool. Also, will be possible to define `loginHint`, `action`, `locale` and the other login parameters
https://www.keycloak.org/docs/latest/securing_apps/#login-options

**Comment by SrMouraSilva** [comment]
An alternative
```tsx
const authIfNeeded = (eventType: AuthClientEvent) => {
  if (eventType === "onReady" && keycloak.authenticated === false) {
    keycloak.login({"scope": "my-custom-scope");
  }
}
  
<ReactKeycloakProvider
    authClient={keycloak}
    initOptions={{checkLoginIframe: false}}
    onEvent={authIfNeeded}
  >
  [...]
</ReactKeycloakProvider>
```
