### ISSUE TITLE
SSRKeycloakProvider.onEvent not triggered when Keycloak host is unreachable  

### ISSUE THREAD

**Issue by markodvornik** [react-keycloak/react-keycloak#128]
**Describe the bug**

_Not sure if this is a bug or feature proposal._

The Keycloak Provider class in `@react-keycloak/ssr` has an `onEvent` method, however none of its predefined events get triggered in a scenario when the Keycloak host is unreachable.

onEvent method:

```
onEvent?: (
    eventType: AuthClientEvent, 
    error?: AuthClientError
) => void;

```

Available events:

```
export declare type AuthClientEvent = 
'onReady' | 'onInitError' | 'onAuthSuccess' | 'onAuthError' | 'onAuthRefreshSuccess' | 'onAuthRefreshError' | 'onAuthLogout' | 'onTokenExpired';

```

Provider setup:

```
export declare class SSRKeycloakProvider extends React.PureComponent<SSRKeycloakProviderProps<SSRAuthClient>, SSRKeycloakProviderState> {
    constructor(props: SSRKeycloakProviderProps<SSRAuthClient>);
    onEvent: (event: AuthClientEvent, error?: AuthClientError | undefined) => void;
    onTokens: (tokens: AuthClientTokens) => void;
    render(): JSX.Element;
}
```

**To Reproduce**
See this [codesandbox](https://codesandbox.io/s/react-keycloak-ssr-v8t6v-v8t6v?file=/pages/_app.tsx) which is based on `Next.js` [example](https://github.com/react-keycloak/react-keycloak-examples/blob/master/examples/nextjs-app/pages/_app.tsx) with added `onEvent` lines from `react-router` [example](https://github.com/react-keycloak/react-keycloak-examples/blob/master/examples/react-router/src/index.tsx).

**Expected behavior**

`onEvent` should trigger some console logging. 

**Proposition**

Perhaps none of the defined events fit this scenario and a new one should be added?

**Additional context**

In a scenario when Keycloak server is unreachable (no network, server down, PWA etc.) React App get stuck at everlasting loading screen. An `onEvent` method could be used to fine tune that behaviour.

```
<SSRKeycloakProvider
      keycloakConfig={keycloakCfg}
      persistor={SSRCookies(cookies)}
      initOptions={keycloakInitOptions}
      LoadingComponent={<LoadingScreen />}
      onEvent={eventLogger}
>
```

**Comment by devtarek** [comment]
Same problem here. Any news on this?

**Comment by dustinteel** [comment]
Same problem here as well, would love to hear if there are any updates.  Also, this ticket submitted to Keycloak seems to be related, so not sure if this is a react-keycloak problem or a keycloak-js problem: https://issues.redhat.com/browse/KEYCLOAK-4883
