### ISSUE TITLE
Endless redirect

### ISSUE THREAD

**Issue by ANicholasson** [react-keycloak/react-keycloak#129]
**Describe the bug**
Not sure if this is a bug, but can't seem to figure out why it's like this. I've seen the examples, and I've read the documentation on keycloak. I have this newly created react application and I'm using keycloak-js and react-keycloak/web as it is required. 

**Code Snippets**
This is my config (keycloak.js):
```js
import Keycloak from "keycloak-js";

// Setup Keycloak instance as needed
const keycloak = new Keycloak({
    realm: "SomeRealm",
    url: process.env.REACT_APP_KEYCLOAK_URL + "/auth/",
    clientId: "app-id",
});

export default keycloak;
```

This is my index file:
```js
// Keycloak
import { ReactKeycloakProvider } from "@react-keycloak/web";
import keycloak from "./keycloak";

const keycloakProviderInitConfig = {
  onLoad: "login-required",
};

ReactDOM.render(
  <ReactKeycloakProvider
    authClient={keycloak}
    initOptions={keycloakProviderInitConfig}
  >
    <React.StrictMode>
      <ChakraProvider>
        <App />
      </ChakraProvider>
    </React.StrictMode>
  </ReactKeycloakProvider>,
  document.getElementById("root")
);
```
So this "should" redirect the user to login if he is not authenticated, but instead, the content of the page is rendered. So I tried an alternative implementation of conditionally showing the content with this snippet:

```js
useEffect(() => {
  if (!keycloak.authenticated) {
    keycloak.login();
  }
}, [keycloak]);

return keycloak.authenticated ? (
  <>
    <Navbar />
    <SomeContent />
  </>
) : null;
```

But that results in an endless loop if the user is authenticated.

Any help would be appreciated :)

**Version**
I'm using the latest version of both keycloak-js and react-keycloak/web

**Comment by WieFel** [comment]
@ANicholasson how did you solve this in the end? (CC: @MikeYakovlev)

**Comment by ANicholasson** [comment]
@WieFel If i remember correctly i had a mismatch between the actual keycloak server i had running and the keycloak-js and react-keycloak versions. Pretty sure i downgraded the versions to match the timeline/version of my keycloak server and it started working without needing any other changes.

**Comment by Elvix10** [comment]
> @ANicholasson how did you solve this in the end? (CC: @MikeYakovlev)

how did you solved it??
