### ISSUE TITLE
Next.js does not render authentication state properly after keycloak login

### ISSUE THREAD

**Issue by jonrosner** [react-keycloak/react-keycloak#135]
**Describe the bug**
I have a basic next.js application that does two things:

1. provide an authentication mechanism using keycloak
2. talk to a backend server that authorizes each request using the keycloak-access-token

I use the @react-keycloak/ssr library to achieve this. The problem now is that after I login and get redirected back to my application the cookie that contains the kcToken is empty. After I refresh my page it works like expected.

I understand that maybe my entire process flow is wrong. If so, what is the "usual" way to achieve what is mentioned above?

**To Reproduce**

Add this stub code to a fresh next.js app:

```javascript
export async function getServerSideProps(context) {
    const base64KcToken = context.req.cookies.kcToken // the cookie that keycloak places after login
    const kcToken = base64KcToken ? Buffer.from(base64KcToken, "base64") : ""

    // the backend server passes the token along to keycloak for role-based authorization
    const res = await fetch(`${BACKEND_URL}/info`, {
            headers: {
                "Authorization": "Bearer " + kcToken 
            }
        })

    const data = await res.json()

    // ... exception handling is left out for readability ...

    return {
        props: {
            data
        }
    }
}

export default function Home({data}) {
    const router = useRouter() // the next.js client side router to redirect to keycloak
    const { keycloak, initialized } = useKeycloak() // keycloak instance configured in _app.js
    if (keycloak && !keycloak.authenticated && keycloak.createLoginUrl) router.push(keycloak.createLoginUrl())
    return (
        <div> ... some jsx that displays data ... </div>
   )
}
```

This process basically works but it feels really bad because a user that gets redirected after login is not able to see the fetched data unless he refreshes the entire page. This is because when getServerSideProps() is called right after redirect the base64KcToken is not there yet.

Also everything related to the login-status (eg. logout button) only gets displayed after ~1sec, when the cookie is loaded by the react-keycloak library.

**Expected behavior**
`data` is displayed in the div after being redirected by keycloak.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version latest

Note: If this is not the right place to ask a question like this I also created a stackoverflow question for this: https://stackoverflow.com/questions/66764930/next-js-does-not-render-authentication-state-properly-after-keycloak-login

**Comment by filippomc** [comment]
The need for refreshing the page can be avoided with the silent check, like this:

```javascript
<SSRKeycloakProvider
       keycloakConfig={keycloakCfg}
       persistor={SSRCookies(cookies)}
            initOptions={{ silentCheckSsoRedirectUri: 'http://' + location + '/silent-check-sso.html' }}
       >
 ...

</SSRKeycloakProvider>
```

while I didn't found a way to avoid the transitory unlogged status. 
I'd like to know whether to fix that transitory is in the plans? I think this a real blocker for any serious use of the library. 
I think a sustainable workaround would be to have a way to understand that the token parsing is someway "pending" in order to postpone the rendering of the page or show a kind of waiting spinner.

**Comment by aakay** [comment]
Is there any progress or workaround on this? I'm struggling with this problem, too.

**Comment by StrongeLeeroy** [comment]
I am also facing this exact issue, no workaround that I've tried has solved the issue without causing even worse side-effects.

**Comment by faaaaabi** [comment]
Same here. After a page transition via a next `<Link>` component, a component using the `useKeycloak` hook, actually doesn't gets a `false` asking keycloak?.authenticated.

Is there a way arround it? Otherwise it would render the usage of the ssr implementation of this library problematic

**Comment by loone96** [comment]
Any update on this? I’m having similar issue.

**Comment by irhamputra** [comment]
My workaround is to create another state with Cookies or LocalStorage or any State Management you wanted to use which I think is bad but it works for my case. After redirect you can use your state to render component or whatever

the cons is you need to manage the state manually and somehow if you wanted to check your state with `keycloak.authenticated` you will get Boolean trap.

e.g I use Cookie

```js
const { keycloak } = useKeycloak();

const handleLogin = (options) => {
   keycloak?.login(options)
   Cookies?.set('isAuthenticated', true)
}
```

**Comment by nvegater** [comment]
Not official solution ?

**Comment by eenchev** [comment]
@irhamputra the callback is called onToken**s**

**Comment by irhamputra** [comment]
@eenchev yes but currently i also face the same problem however there is no official solution and I need to persist the Auth State from Keycloak and Keycloak will run in client only.

**Comment by strandseter** [comment]
Any updates on this?

**Comment by C-4PO** [comment]
I need a solution for this too. I am stuck on the no cookies on initial load part. Still deciphering this else I have to scrap everything and use `next-auth`.
