### ISSUE TITLE
set checkLoginIframe=false and then get error=login_required

### ISSUE THREAD

**Issue by fangwohung** [react-keycloak/react-keycloak#138]
I'm using @react-keycloak/ssr 3.3.0, keycloak-js 12.0.4 and nextjs 10.1.3.
I have to set checkLoginIframe=false in order to initialize keycloak by access token and refresh token.
However, if a user is not logged in (both refresh token and access token are empty), the page will be reloaded. Then, I get this link
http://localhost:3000/#error=login_required&state=9d3ee440-4001-464d-8926-ec1985dd1359. 
But if I try initializing KeycloakInstance of keycloak-js by the same configuration, everything is fine. 
My codes
```js
 const keycloakConfig = {
        clientId: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID,
        realm: process.env.NEXT_PUBLIC_KEYCLOAK_REALM,
        url: process.env.NEXT_PUBLIC_KEYCLOAK_URL
    };
    return (
        <SSRKeycloakProvider
            keycloakConfig={keycloakConfig}
            autoRefreshToken={true}
            initOptions={{
                // onLoad: "check-sso",
                // promiseType: "native",
                token: credentials.accessToken,
                refreshToken: credentials.refreshToken,
                checkLoginIframe: false,
                enableLogging: process.env.NEXT_PUBLIC_KEYCLOAK_ENABLE_LOGGING === "true"
            }}
            LoadingComponent={<BackdropLoading open={true} />}
            persistor={SSRCookies(cookies)}>
           {/* other components */}
        </SSRKeycloakProvider>
    );
```

**Comment by tobiasfrei** [comment]
same here. any news?

**Comment by fangwohung** [comment]
> same here. any news?

Now, I'm using this [next-auth-keycloak](https://next-auth.js.org/providers/keycloak) but the next auth just supports the nextjs

**Comment by sorokinvj** [comment]
@fangwohung Could you please share your setup with next-auth-keycloak? I tried to implement it, but has a lot of uncertainty and couldn't figured out the right init (and how to pass initOptions)

Here with react-keycloak/ssr I am getting a token, but then same issue - next keep reloading an app and I could not understand why

**Comment by fangwohung** [comment]
> @fangwohung Could you please share your setup with next-auth-keycloak? I tried to implement it, but has a lot of uncertainty and couldn't figured out the right init (and how to pass initOptions)
> 
> Here with react-keycloak/ssr I am getting a token, but then same issue - next keep reloading an app and I could not understand why

If you're using next-auth, you dont have to use keycloak-js client because your keycloak tokens (access token and refresh token) will be stored within next-auth session and then you can get session data by calling useSession (next-auth hook).
I think you can try next-auth with google provider in order to understand how next-auth works, you also have to implement [Refresh Token Rotation](https://next-auth.js.org/tutorials/refresh-token-rotation) on your own. You must remember that the next-auth token is different from keycloak tokens which are stored within session

**Comment by sorokinvj** [comment]
> > @fangwohung Could you please share your setup with next-auth-keycloak? I tried to implement it, but has a lot of uncertainty and couldn't figured out the right init (and how to pass initOptions)
> > Here with react-keycloak/ssr I am getting a token, but then same issue - next keep reloading an app and I could not understand why
> 
> If you're using next-auth, you dont have to use keycloak-js client because your keycloak tokens (access token and refresh token) will be stored within next-auth session and then you can get session data by calling useSession (next-auth hook). I think you can try next-auth with google provider in order to understand how next-auth works, you also have to implement [Refresh Token Rotation](https://next-auth.js.org/tutorials/refresh-token-rotation) on your own. You must remember that the next-auth token is different from keycloak tokens which are stored within session

Unfortunately, I bound to keycloak because of the SSO and backend team preferences

**Comment by fangwohung** [comment]
> > > @fangwohung Could you please share your setup with next-auth-keycloak? I tried to implement it, but has a lot of uncertainty and couldn't figured out the right init (and how to pass initOptions)
> > > Here with react-keycloak/ssr I am getting a token, but then same issue - next keep reloading an app and I could not understand why
> > 
> > 
> > If you're using next-auth, you dont have to use keycloak-js client because your keycloak tokens (access token and refresh token) will be stored within next-auth session and then you can get session data by calling useSession (next-auth hook). I think you can try next-auth with google provider in order to understand how next-auth works, you also have to implement [Refresh Token Rotation](https://next-auth.js.org/tutorials/refresh-token-rotation) on your own. You must remember that the next-auth token is different from keycloak tokens which are stored within session
> 
> Unfortunately, I bound to keycloak because of the SSO and backend team preferences

Before using next auth, I had this issue and then used pure keycloak js for nextjs, I handled everything on client side, but the drawback of keycloakjs is that I cannot get the access token on server side and cannot take advantage of SSR. I havent implemented SSO for next auth yet, so you have to implement SSO feature by yourself if you really want to use next auth

**Comment by Shane98c** [comment]
I'm seeing this same issue with the following configuration in a standard react app:
```
initOptions={{
        onLoad: "check-sso",
        checkLoginIframe: false,
        promiseType: "native",
      }}
```
The page loads once briefly, immediately goes blank while `error=login_required` flashes in the url, and then the page loads once more with the error in the url cleared and everything working as expected. A time consuming and ugly dance.

Anyone else seeing similar or have any success finding their way around this problem?

Edit: this same issue is reproducible with stand-alone keycloak, so doesn't seem to be related to anything implemented in this library.

**Comment by edivanteixeira** [comment]
This error is because the version of Keycloak-js is different from your server.
