### ISSUE TITLE
The automatic base64 encoding makes token cookie too large to save

### ISSUE THREAD

**Issue by nilsnh** [react-keycloak/react-keycloak#139]
**Describe the bug**
Our Keycloak installation returns a token with length approximately around 3800 characters long. Technically that should be short enough to be stored as a cookie but it fails because when saving the `SSRCookies` persistor base64 encodes the token which makes it around 5000 characters length.

**To Reproduce**

1. Use `<SSRKeycloakProvider />` with the `SSRCookies` persistor.
2. Perform login and receive tokens token + idToken.
3. If the token length is for instance 3800 characters long it will get base64 encoded into a 5000 character long string before being stored as a cookie. And Firefox will complain that the 5000 character kcToken cookie is too long to store.

**Expected behavior**

I expected the token cookie to be successfully set.

**Desktop (please complete the following information):**

- OS: macOS 11.2.3 
- Browser Firefox
- Version 87

**Additional context:**

There might off course be good reasons as to why it is necessary to encode / decode these token strings. If that is the case, feel free to close this issue. 

Many thanks for creating this solid library. 😄

**Comment by aakay** [comment]
Hi @nilsnh, have you found any solution to this?

**Comment by stevefiedler** [comment]
Awesome fix!  My kcToken kept getting larger with every realm I created, so it always broke at some point when trying to persist a cookie.  it also failed in Chrome, but did not have an error appear on the console, so I didn't detect it until I ran it in Firefox.

**Comment by aakay** [comment]
@nilsnh hi nils, sorry, i've somehow missed your response. thanks for the help. this looks like a good solution. thank you.
