### ISSUE TITLE
Acces token is not refreshed after expiration time is met and refresh token is still valid

### ISSUE THREAD

**Issue by Ronaldvdh-ISAAC** [react-keycloak/react-keycloak#147]
**Describe the bug**
When the expiration time of the access token is past, the new token is not fetched

**To Reproduce**

1. Login in react-native app successfully
2. Reload the app and notice auto login because refresh token is still valid
3. Wait for token to expire (i set it for testing purposes in the keycloak console to 1 minute but it also happened when it was on 5 minutes)
5. Observe 'OnTokenExpired' event is fired by the ReactNativeKeycloakProvider
6. Observe 'UpdateToken' is triggered (i put some console.logs)
7. Observe it takes the short escape as it already found a defined promise
```
if (this.refreshTokenPromise) {
      return this.refreshTokenPromise;
    }
```
8. No new acces token is fetched so next api call is with the expired access token which results in 401 (which is correct as the token is expired)
9. Reloading the app will use the valid refreshtoken to fetch a new accesstoken and voila api calls are valid again without re-entering credentials. until the token with logging in is expired and no new tokens are retrieved with the updateToken call.

**Expected behavior**
I expect after returning to the react-native app that the access token will be tried to be updated after it expires.

**Screenshots**
![image](https://user-images.githubusercontent.com/20579217/122565926-47282200-d047-11eb-8ba9-513129d2e15e.png)

Updated `client.js` in node_modules to set the console.logs:
```
async updateToken(minValidity = 5) {
    if (!this.refreshToken) {
      throw new Error('missing refreshToken');
    }

    console.log('Update token root: ', {refreshTokenPromise: this.refreshTokenPromise})
    if (this.refreshTokenPromise) {
      return this.refreshTokenPromise;
    }

    this.refreshTokenPromise = new Promise(async (resolve, reject) => {
      let shouldRefreshToken = false;

      if (minValidity === -1) {
        shouldRefreshToken = true;
        this.logInfo('[KEYCLOAK] Refreshing token: forced refresh');
      } else if (!this.tokenParsed || this.isTokenExpired(minValidity)) {
        shouldRefreshToken = true;
        this.logInfo('[KEYCLOAK] Refreshing token: token expired');
      }

      if (!shouldRefreshToken) {
        resolve(false);
        this.refreshTokenPromise = undefined;
        console.log('!shouldRefreshToken', {refreshTokenPromise: this.refreshTokenPromise})
        return;
      }

      const tokenUrl = this.endpoints.token();
      const params = new Map();
      params.set('client_id', this.clientId);
      params.set('grant_type', 'refresh_token');
      params.set('refresh_token', this.refreshToken);
      let timeLocal = new Date().getTime();

      try {
        const tokenResponse = await this.adapter.refreshTokens(tokenUrl, (0, _url.formatQuerystringParameters)(params));
        this.logInfo('[KEYCLOAK] Token refreshed');
        timeLocal = (timeLocal + new Date().getTime()) / 2;
        this.setToken(tokenResponse.access_token, tokenResponse.refresh_token, tokenResponse.id_token, timeLocal); // Notify onAuthRefreshSuccess event handler if set

        this.onAuthRefreshSuccess && this.onAuthRefreshSuccess();
        resolve(true);
      } catch (err) {
        this.logWarn('[KEYCLOAK] Failed to refresh token'); // Clear tokens

        this.clearToken(); // Notify onAuthRefreshError event handler if set

        this.onAuthRefreshError && this.onAuthRefreshError();
        reject();
      }

      this.refreshTokenPromise = undefined;
      console.log('Token Response: ', {refreshTokenPromise: this.refreshTokenPromise})
    });
    return this.refreshTokenPromise;
  }
```

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: iOS 14.5
- Browser: stock browser (safari)

**Additional context**
As far as i could see there is only one spot where `this.refreshTokenPromise` is set and this is in the `updateToken` function. And it seems that the code that sets this promise as undefined is hit, but when coming back to the app it is already set without any token call being executed.

P.S. Currently im running patch-package in my app and i just comment out the check for an existing refreshTokenPromise which solves the 401 error after your first access token is expired.

**Comment by stweiz** [comment]
I think, I have the same issue, if the toxen expires and I switch to another host, but the same application.

Steps to reproduce:

1. Let the React app listen to 2 domains. http://react-test.com http://react-test-second.com
2. Go to http://react-test.com
3. Login on the page.
4. Wait until the access token expires (usually 5 min).
5. Now enter http://react-test-second.com in the same browser tab

When you enter the other site, you won't get a new access token. After a manually refresh the new access token is fetched.

For me it's very problematic, because I do a GraphQL request on server side and can't/don't want to refresh the token their. It should happen on client site, before the prerendered page is requested with the authorization header.

I'm looking for a solution. Do you already have a workaround?

**Comment by Jrodseth** [comment]
This is an outstanding issue.
