### ISSUE TITLE
404 Errors - Loading Keycloak Loginpage

### ISSUE THREAD

**Issue by Excel1** [react-keycloak/react-keycloak#150]
**Describe the bug**
I implemented the Keycloak-js and configure all needed settings. By loading the page with the Login Button i recieve 404 errors without clicking on the login Button or Call the Login Page. 

**To Reproduce**

1. Implement and setup keycloak js
2. Load the default home page without login
3. error in console 
https://my.domain/auth/realms/myrealm/protocol/openid-connect/3p-cookies/step1.html 404
Not Found

https://my.domain/auth/resources/p1rai/login/material-jk-theme/js/nodelist-foreach.js 404
Not Found

https://my.domain/auth/resources/p1rai/login/material-jk-theme/js/nodelist-foreach.js 404
Not Found

Uncaught TypeError: this.root_ is null

**Expected behavior**
zero errors

**Desktop (please complete the following information):**

- OS: Arch-Linux
- Browser Firefox
- Version 88.0.1

**Additional context**
The errors could be normal by opening the keycloak loginpage cause the theme but why did they get loaded in the background without visiting Login Page and without being logged in?

Also:
1. Click login
2. Get redirected to Keycloak
3. Log - In
4. Get redirected to Application
5. NOT LOGGED IN - No Errors in console and no tokens get logged.
6. Click Login Again - Get redirected to Application - NOT LOGGED IN - No Errors in console and no tokens get logged.
7. Go to Keycloak Loginpage directly: Iam logged in (there)

index.tsx
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import reportWebVitals from './reportWebVitals';
import LandingPage from "./LandingPage";
import keycloak from "./keycloak";
import { ReactKeycloakProvider } from '@react-keycloak/web'

const eventLogger = (event: unknown, error: unknown) => {
    console.log('onKeycloakEvent', event, error)
}

const tokenLogger = (tokens: unknown) => {
    console.log('onKeycloakTokens', tokens)
}

ReactDOM.render(
  <React.StrictMode>
      <ReactKeycloakProvider authClient={keycloak}
                             onEvent={eventLogger}
                             onTokens={tokenLogger}>
          <LandingPage />
      </ReactKeycloakProvider>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

LandingPage.tsx
```
import React, {useCallback} from 'react';
import Button from '@material-ui/core/Button';
import { useKeycloak } from '@react-keycloak/web'

export default function LandingPage() {
    const { keycloak } = useKeycloak()

    const login = useCallback(() => {
        keycloak?.login()
    }, [keycloak])

    return (
    <div>
        <div>{`User is ${
            !keycloak.authenticated ? 'NOT ' : ''
        }authenticated`}</div>

        {!!keycloak.authenticated && (
            <Button variant="contained" onClick={() => keycloak.logout()}>Logout</Button>
        )}

        <Button variant="contained" onClick={login}>
            Login
        </Button>
    </div>
    );
}
```

keycloak.ts
```
import Keycloak from 'keycloak-js';

// Setup Keycloak instance as needed
// Pass initialization options as required or leave blank to load from 'keycloak.json'
const keycloak = Keycloak({
    url: 'https://my.domain/auth',
    realm: 'myrealm',
    clientId: 'realmid',
});

export default keycloak;
```

**Comment by Excel1** [comment]
#107 - This explains why, but is it really needed? How to deactivate it or change it if it needed?

**Comment by vlkpa** [comment]
same problem... any update?

**Comment by Excel1** [comment]
@vlkpa 

https://github.com/dsb-norge/vue-keycloak-js/issues/94

You can use Historymode as a  "dirty" workaround.

**Comment by Fornori** [comment]
Any updates?

**Comment by vlkpa** [comment]
Check your keycloak server and keycloak-js version, it should be same.

> Any updates?
