### ISSUE TITLE
Property 'login' does not exist on type 'SSRAuthClient'.

### ISSUE THREAD

**Issue by zaventh** [react-keycloak/react-keycloak#152]
**Describe the bug**

`keycloak` instance does not appear to have a `login()`.

**To Reproduce**

```typescript
import {useKeycloak} from "@react-keycloak/ssr";
const { keycloak } = useKeycloak<KeycloakInstance>()
keycloak?.login()
```

```
TypeError: keycloak.login is not a function
    at LoginRequired (webpack-internal:///./src/components/LoginRequired.tsx:18:66)
```

**Expected behavior**

`keycloak.login()` should exist.

**Additional context**

According [to the examples](https://github.com/react-keycloak/react-keycloak-examples/blob/master/examples/nextjs-app/pages/profile.tsx#L19) the `useKeycloak` function should give me a `KeycloakInstance` type (from `keycloak-js`), which does have `login()`. It appears to return an `SSRAuthClient` object, which extends from `AuthClient` which does not have `login()` at least on its type definition.

```
$ npm list keycloak-js @react-keycloak/ssr
[redacted]@0.1.0 [redacted]
├── @react-keycloak/ssr@3.3.0 
└── keycloak-js@14.0.0 
```

**Comment by Mheaus** [comment]
Maybe it could be added to the `AuthClient` type in `packages/core/src/types.ts` ?

**Comment by Mheaus** [comment]
I've created a pull request about it : https://github.com/react-keycloak/react-keycloak/pull/155.

**Comment by Mheaus** [comment]
@panz3r did you saw this ?
