### ISSUE TITLE
CORP error on localhost

### ISSUE THREAD

**Issue by Syntarex** [react-keycloak/react-keycloak#162]
Hi! My versions:

React: 17.0.2
ReactDOM: 17.0.2
@react-keycloak/web: 3.4.0
Keycloak: 15.0.1 

Everything works fine if I host my react app and keycloak on a server. The react app got the url `ui.domain.com` and keycloak got `id.domain.com`.

If I'm trying to run my react app locally on `https://localhost:1234`, it throws this http error:

```
GET https://id.domain.com/auth/realms/REALMNAME/protocol/openid-connect/3p-cookies/step1.html
not-set cross-origin-resource-policy
```

I set the base-, admin- and redirect-url to `https://localhost:1234`. I also added `+` to web origins. The client type is public.

Same result if I'm hosting keycloak on `http://localhost:8080`

I'm not sure if this is a problem with my keycloak configuration or react-keycloak. 

Thanks for your help in advance!

**Comment by exaucae** [comment]
Add `*` instead of `+` to web origins.

**Comment by remitestut** [comment]
Same problem, any solutions ?

**Comment by itsalb3rt** [comment]
Are you running this inside a container?

Btw, check if your client configuration is like that;

Keycloak admin portal -> clients -> myClient -> in the bottom of the page;

![image](https://user-images.githubusercontent.com/35310226/153632968-9efe4cd5-cbfb-4a9a-ae5c-5480ce03f11b.png)

**Comment by Syntarex** [comment]
Oh yeah I did this. I solved the issue by temporally adding the http headers to my apache configuration. Works fine for me. :)
