### ISSUE TITLE
Is autoRefreshToken default value true?

### ISSUE THREAD

**Issue by newpost** [react-keycloak/react-keycloak#163]
https://github.com/react-keycloak/react-keycloak/blob/b97611601f5198df28307f0716c738829beb0d93/packages/core/src/provider.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L26

**Comment by panz3r** [comment]
Yes, `autoRefreshToken` default value is `true` as stated in the JSDoc.

**Comment by newpost** [comment]
When I do not set this value, it does not automatically update the token.
