### ISSUE TITLE
Can you add custom login connection or maybe how to enable these feature can you give me a trick

### ISSUE THREAD

**Issue by mthnakdag** [react-keycloak/react-keycloak#166]
I connect with keycloak protocols with a post method get token and refresh token but how to assign these values to be able to use both callbacks and other functions in keycloak ???? PLEASE GIVE ME A TRICK

WANTED REQUEST
- give a function parameters: username, password and these functions return only keycloak promise. Function purpose giving username and password login keycloak auth without using default keycloak login page

> Normally, assign operator is not working because when i re-rendering page, tokens  are forget
> ❌❌ keycloak.token = response.data.access_token ❌❌

```js
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'client_id': <keycloak-client>,
  'grant_type': 'password',
  'username': <username>,
  'password': <password>
});
var config = {
  method: 'post',
  url: `${<keycloak-auth-server>}/realms/${<keycloak-realm>}/protocol/openid-connect/token`,
  headers: { 
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  data : data
};

axios(config)
.then(function (response) {
  //TODO: THIS AREA FOR RESPONSE HOW TO SET TOKEN AND REFRESH TOKEN TO KEYCLOAK NORMALLY ASSIGNED ONLY WORKED RE-RENDERED HOW TO USE ALL KEYCLOAK-JS FUNCTIONALITIES
  console.log(JSON.stringify(response.data));

})
.catch(function (error) {
  console.log(error);
});
```

**Comment by guirkgumbo** [comment]
Did you get any further with this? It would be nice to leverage all the functionality of @react-keycloak/web while using a custom login page.

**Comment by mthnakdag** [comment]
Hi @guirkgumbo  I use design my page with keycloakify and react/keycloak/web maybe and solve my problem partially but when using two of them together tomcat logs is  become crazy for this situation(close logs warnings) thank you for your response
