### ISSUE TITLE
Gastby build error window is not defined

### ISSUE THREAD

**Issue by big8extreme** [react-keycloak/react-keycloak#76]
I followed the gatsby exemple and with gatsby develop everything was working. but when building i had window is not defined error.

i tested many things:
`typeof window !== undefined`

followed this https://www.gatsbyjs.org/docs/debugging-html-builds/ but nothing work.

**Comment by panz3r** [comment]
Hi @big8extreme ,

That's kind of a strange error, since `react-keycloak` is attached only to the `client-side` during the `gatsby` build it should not throw that error.

I'll need to take a look at that but I'd say that Gatsby might not be currently fully supported by the current implementation.

**Comment by Dangercoder** [comment]
I'm having the same issue with nextjs. 

Line 63 is blowing up for me:
https://github.com/keycloak/keycloak/blob/9.0.2/adapters/oidc/js/src/main/resources/keycloak.js
"window is not defined"

**Comment by pratik-walkhade** [comment]
I'm having the same issue with nextjs.

When I am trying configure silentCheckSsoRedirectUri.

**Comment by panz3r** [comment]
Hi @Dangercoder,

Thanks for your feedback.

Can you please open a new issue with more details about your setup?
In particular:
- which module are you using (`@react-keycloak/ssr` or `@react-keycloak/nextjs`)
- which version of the module
- which version of `keycloak-js` package
- properties passed to the `KeycloakProvider`

Thanks in advance.

**Comment by kriswuollett** [comment]
Here's my `package.json` for nextjs with which I also get the `window` not defined error:

```json
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@react-keycloak/ssr": "^2.0.0-alpha.1",
    "cookie": "^0.4.1",
    "keycloak-js": "^10.0.2",
    "next": "9.4.4",
    "next-absolute-url": "^1.2.2",
    "nextjs": "0.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@types/cookie": "^0.4.0",
    "@types/node": "^14.0.18",
    "@types/react": "^16.9.41",
    "typescript": "^3.9.6"
  }
}
```

Configuration properties used with `ServerPersistors.SSRCookies`:

```javascript
    const keycloakCfg: KeycloakConfig = {
        realm: process.env.NEXT_PUBLIC_AUTH_REALM,
        url: process.env.NEXT_PUBLIC_AUTH_URL,
        clientId: process.env.NEXT_PUBLIC_AUTH_CLIENT_ID,
    };

    const keycloakInitCfg: KeycloakInitOptions = {
        onLoad: "check-sso",
    };
```

Complicating factor is that #75 is not resolved yet (`npm run dev` only compiles when importing `ServerPersistors` but VS Code highlights the import saying that isn't exported)

**Comment by tiaanduplessis** [comment]
I believe #82 also resolves this issue.

**Comment by EpicEric** [comment]
My current workaround is to defer loading of `keycloak-js` (for example, with [Loadable Components](https://loadable-components.com/docs/library-splitting/)), and use a mock Keycloak instance when it's not initialized. For example:

```tsx
const KeycloakLib: any = loadable.lib(() => import("keycloak-js"))

const MockKeycloakInstance: any = {
  init: () => Promise.resolve(false),
  login: () => Promise.resolve(),
  logout: () => Promise.resolve(),
  register: () => Promise.resolve(),
  accountManagement: () => Promise.resolve(),
  createLoginUrl: () => null,
  createLogoutUrl: () => null,
  createRegisterUrl: () => null,
  createAccountUrl: () => null,
  isTokenExpired: () => true,
  updateToken: () => Promise.resolve(false),
  clearToken: () => {},
  hasRealmRole: () => false,
  hasResourceRole: () => false,
  loadUserProfile: () => Promise.resolve({}),
  loadUserInfo: () => Promise.resolve({}),
}

// ...

return (
  <KeycloakLib
    fallback={
      <ReactKeycloakProvider
        authClient={MockKeycloakInstance}
        isLoadingCheck={() => false}
      >
        {children}
      </ReactKeycloakProvider>
    }
  >
    {({ default: Keycloak }: KeycloakDefault) => (
      <ReactKeycloakProvider
        authClient={Keycloak({ /* ... */ })}
        initOptions={{
          onLoad: "check-sso",
          silentCheckSsoRedirectUri:
            window.location.origin + withPrefix("/silent-check-sso.xhtml"),
          pkceMethod: "S256",
          flow: "standard",
        }}
        isLoadingCheck={() => false}
      >
        {children}
      </ReactKeycloakProvider>
    )}
  </KeycloakLib>
)
```
