### ISSUE TITLE
Next JS windows not define while trying use silentCheckSsoRedirectUri 

### ISSUE THREAD

**Issue by pratik-walkhade** [react-keycloak/react-keycloak#78]
I am getting an error - window is no define while trying to use silentCheckSsoRedirectUri.

Versions I am using:
"keycloak-js": "^9.0.2"
"@react-keycloak/nextjs": "^2.0.0-beta.2"

Code: 
`const keycloakCfg = {
  url: 'my url',
  realm: 'my realm',
  clientId: 'my client'
};

const initOptions = {
onLoad: 'check-sso',
      promiseType: 'native',
      silentCheckSsoRedirectUri:
        window.location.origin + '/silent-check-sso.html'
    }
`

`<SSRKeycloakProvider
          keycloakConfig={keycloakCfg}
          persistor={Persistors.Cookies(cookies)}
          initConfig = {initOptions}
        >
        </SSRKeycloakProvider>`

Please help me out.

Thanks in advance

**Comment by Dangercoder** [comment]
It's probably because the code is not executing in the browser.
A workaround is to hardcode it: **http://localhost:3000/silent-check-sso.html**

**Comment by pratik-walkhade** [comment]
Hi,
Thanks for the solution but the solution that you have shared is still not working. After implementing (adding hardcoded URL) page is not getting refresh but I am not able to logout from the application.

`Code:
`const keycloakCfg = {
url: 'my url',
realm: 'my realm',
clientId: 'my client'
};

const initOptions = {
onLoad: 'check-sso',
promiseType: 'native',
silentCheckSsoRedirectUri:
'http://localhost:3000/silent-check-sso.html'
}`

`<SSRKeycloakProvider keycloakConfig={keycloakCfg} persistor={Persistors.Cookies(cookies)} initConfig = {initOptions} > </SSRKeycloakProvider>`
