### ISSUE TITLE
React Keycloak -> iframe refuses to display

### ISSUE THREAD

**Issue by jmazagao** [react-keycloak/react-keycloak#83]
**Describe the bug**
I'm following the example of react-router, and I only copy and paste the example into my codebase, but using the latest version of react-keycloak and my page doesn't run the app and doesn't run the app, but, when I change to the version of the example runs ok, what's happening their?

**To Reproduce**
package.json
```
{
  "name": "keycloak-guide",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-keycloak/web": "^2.1.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "axios": "^0.19.2",
    "keycloak-js": "^11.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
Error at the console: 
Refused to frame 'http://localhost:8080/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

**Expected behavior**
I expect to see the page of app example.

**Comment by jmazagao** [comment]
When I change the 'keycloak-js' dependency to 10.0.1 it works, but in 11.0.0 version isn't working with the latest version

**Comment by panz3r** [comment]
Hi @jmazagao ,

Thanks for your feedback

> Possible problem with keycloak-js and not with the react-keycloak component

as you already said, this issue seems more related to `keycloak-js` itself than to `react-keycloak`, I tried to have a look at the latest changelog for `Keycloak` (see [here](https://www.keycloak.org/2020/07/keycloak-1100-released.html)) and on their issue tracker (see [here](https://issues.redhat.com/projects/KEYCLOAK/issues)) but couldn't find any related info, you can try to open a new issue there.
