### ISSUE TITLE
Getting a SecurityError when reloading screens on ReactKeycloak with keycloak-js plugin

### ISSUE THREAD

**Issue by rahulbrahmal** [react-keycloak/react-keycloak#88]
**Describe the bug**
I am getting a security error whenever I refresh a valid route on keycloak. The error message is attached below. Basically, it looks like keycloak is injecting a URL param state into the browser, but the history state object doesn't seem to have the baseUrl (in this case http://localhost:3000).

I am using React Router v4 for routes.

**To Reproduce**
Log in via keycloak (redirect to Keycloak Login, authenticates, redirects to page.

When I manually invoke a reload, a SecurityError appears.

**Expected behavior**
When I reload the page, it should render the screen without the Security Error.

**Screenshots**
<img width="1081" alt="Screen Shot 2020-08-11 at 3 23 53 PM" src="https://user-images.githubusercontent.com/24690504/89916166-d6bea200-dbe6-11ea-84f7-7fe7e642c6b1.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome, Safari, Brave ...

**Additional context**

**Comment by tloriato** [comment]
We have investigated and we think it's something related to the serviceWorker of the CRA.
