### ISSUE TITLE
Is there a way to refresh token in server-side?!

### ISSUE THREAD

**Issue by elyash14** [react-keycloak/react-keycloak#89]
I'm working on a project with NextJs and it has a SSO server. The keycloak tokens frequently expire in a short period of time.On the other hand I get user information from another server with API and token. Currently this process at the getInitialProps and i'm using KcToken cookie. If token is valid, everything works fine. but when token expire the API return 401.
Is there a way to refresh token in server side? I used getKeycloakInstance() function but it's not working on the server side.
Sorry about my English.

**Comment by EpicEric** [comment]
Adding PKCE will use Code Flow (instead of Implicit Flow), which should enable Refresh Tokens. Here's an example:

```diff
 <KeycloakProvider
   ...
   initConfig={{
     promiseType: 'native',
     onLoad: 'check-sso',
     silentCheckSsoRedirectUri: window.location.origin + '/silent-check-sso.xhtml',
+    pkceMethod: 'S256',
     flow: 'standard',
   }}
   ...
 >
```

Just make sure that "Proof Key for Code Exchange Code Challenge Method" is set in your public client.

**Comment by elyash14** [comment]
I'm using the code flow, and refresh token every five minutes. Everything works fine on the client-side. I want to refresh the token on the server-side. currently, I'm saving refresh token in the cookie and use it for refresh token in the server-side with a post request directly.
`const url = `${config.SSO_AUTH_SERVER_URL}/realms/${config.SSO_REALM}/protocol/openid-connect/token`;
        const result = await axios.post(
            url,
            qs.stringify({
                refresh_token: refreshToken,
                grant_type: 'refresh_token',
                client_id: config.SSO_PUBLIC_CLIENT_ID,
            }),
            { headers: { 'content-type': 'application/x-www-form-urlencoded' } },
        );
        return result.data.access_token`

**Comment by beau6183** [comment]
@panz3r any update on that version?
