### ISSUE TITLE
Brave browser keeps reloading

### ISSUE THREAD

**Issue by Jesusz0r** [react-keycloak/react-keycloak#91]
**Describe the bug**
Hey guys. I recently started using Brave browser and I noticed that my application kept reloading. I think it has something to do with refreshing the token because it goes to this url every time it refreshes

`http://localhost:3000/#state=f33b16b5-57a9-4fd6-bf3a-9d7f4c3505cb&session_state=8009dfe4-11df-4366-a0db-db85f35a2469&code=c66bbb7b-a32b-46ff-98f4-2c6e47708525.8009dfe4-11df-4366-a0db-db85f35a2469.d7f13ad3-f6a9-422f-9b6e-42b2b43f3731`

**To Reproduce**

1. Use Brave browser
2. Go to your application use Keycloak
4. See it refresh around every 10 seconds

**Expected behavior**
Not visibly refresh the website

**Desktop (please complete the following information):**

- Operating System: MacOS
- Browser: Brave
- Version: Latest

**Comment by obouchta** [comment]
I'm facing the same issue but more like 2 refreshes by second.
I created the following issue but I don't know if you have some good news about this ?
https://github.com/react-keycloak/react-keycloak/issues/93

**Comment by panz3r** [comment]
Related to #93
