### ISSUE TITLE
History back from login page

### ISSUE THREAD

**Issue by akos96kov** [react-keycloak/react-keycloak#92]
**The problem:**

When I'm calling the `keycloak.login()` method, it redirects to the login page.
Then I'm clicking on browser's history back button, and it is going back **2 pages** instead of **1**.

**Example** (locations and actions):
- localhost:8080
[naviagating to localhost:8080/employee (with react router's `history.push()` method)]
- 8080/employee
[calling `keycloak.login()` method]
- keycloak login page
[clicking on browsers history back button]
- localhost:8080

**Versions:**
@react-keycloak/web: 2.1.1
keycloak-js: 10.0.2
react: 16.12.0
react-router-dom: 5.1.2

**Comment by mattishii** [comment]
This is just keycloak, not this wrapper library. It's using location.replace, not location.assign. If you want to be able to use browser back, then instead of keycloak.login() use 
```
const url = keycloak.createLoginUrl()
location.assign(url)
```
