### ISSUE TITLE
react-testing-library build failure, cannot read property `catch` of undefined

### ISSUE THREAD

**Issue by tomvothecoder** [react-keycloak/react-keycloak#95]
**Describe the bug**
My build fails when upgrading `react-keycloak` package version from 2.1.1 to 2.1.4.
I isolated the build failure specifically to upgrading `react-keycloak`. I am using `jest` and `react-testing-library` for testing.

Example error below:
- `TypeError: Cannot read property 'catch' of undefined`
- `console.error node_modules/react-dom/cjs/react-dom.development.js:19527
    The above error occurred in the <KeycloakProvider> component:
        in KeycloakProvider (at AuthContext.test.tsx:44)`

Example of test code:
```
const keycloak: KeycloakInstance = {
  // Optional
  authenticated: false,
  userInfo: {},
  // Required
  accountManagement: jest.fn(),
  clearToken: jest.fn(),
  createAccountUrl: jest.fn(),
  createLoginUrl: jest.fn(),
  createLogoutUrl: jest.fn(),
  createRegisterUrl: jest.fn(),
  isTokenExpired: jest.fn(),
  hasRealmRole: jest.fn(),
  hasResourceRole: jest.fn(),
  init: jest.fn(),
  loadUserInfo: jest.fn(),
  loadUserProfile: jest.fn(),
  login: jest.fn(),
  logout: jest.fn(),
  register: jest.fn(),
  updateToken: jest.fn(),
};

 it('renders using keycloak provider', async () => {
    jest.useFakeTimers();

    const { getByTestId, getByText } = render(
    <KeycloakProvider keycloak={{ ...keycloak, token: 'token'  }}>
         <AuthProvider>
          <div data-testid="authProvider">
            <p>renders</p>
          </div>
        </AuthProvider>
    </KeycloakProvider>
    );

    // Wait for render to get user auth info
    const authProvider = await waitFor(() => getByTestId('authProvider'));
    expect(authProvider).toBeTruthy();

    // Wait for re-render to get user info
    await waitFor(() => getByTestId('authProvider'));

    // Check children renders
    const renderResult = await waitFor(() => getByText('renders'));
    expect(renderResult).toBeTruthy();

    act(() => {
      jest.advanceTimersByTime(295000);
    });

    await waitFor(() => getByTestId('authProvider'));

    // Revert back to real timer
    jest.useRealTimers();
  });
```

**Expected behavior**
Tests should pass unless there is a breaking change by upgrading from 2.1.1 to 2.1.4. I did note that `@react-keycloak/core` is now on 2.2.1. 

For now, I will be pinning to 2.1.1.

**Comment by panz3r** [comment]
Hi @tomvothecoder ,

Thanks for your feedback, from the code you posted I think I know where your problem comes from.
The `Keycloak` stub you are using is not correct, in particular the `init` method should return a `Promise` and not be a simple `jest.fn()`.

The reason you are seeing the issue when upgrading to `@react-keycloak/web` `2.1.4` is because a check was added to the `init` call internally but that's not been marked as a minor version because `keycloak` has been returning a `Promise` since version `9.0.2` (which caused the `@react-keycloak` versions to be moved to the `2.x` major).

Let me know if this helps you fix your test issues.

**Comment by tomvothecoder** [comment]
Hi @panz3r,

Thanks for the quick follow up. Nice catch! I was able to fix the issue by updating the `init` method in my `Keycloak` stub. My build is passing again 👍 

```
const keycloak: KeycloakInstance = {
  // Optional
  authenticated: false,
  userInfo: {},
  // Required
  accountManagement: jest.fn(),
  clearToken: jest.fn(),
  createAccountUrl: jest.fn(),
  createLoginUrl: jest.fn(),
  createLogoutUrl: jest.fn(),
  createRegisterUrl: jest.fn(),
  isTokenExpired: jest.fn(),
  hasRealmRole: jest.fn(),
  hasResourceRole: jest.fn(),
  init: jest.fn(() => Promise.resolve({})),
  loadUserInfo: jest.fn(),
  loadUserProfile: jest.fn(),
  login: jest.fn(),
  logout: jest.fn(),
  register: jest.fn(),
  updateToken: jest.fn(),
};
```
