### ISSUE TITLE
SSR: Clarification on when auth redirects occur (every refresh?)

### ISSUE THREAD

**Issue by mattishii** [react-keycloak/react-keycloak#98]
**Describe the bug**
It seems like the default configuration automatically does an auth redirect every page load? Is that an accurate statement? If so, is there any way to change it so that the redirect is opt-in/controlled from application code?

**To Reproduce**
1. Load a page, note that it redirects to keycloak.
2. Refresh the same page. 
3. It will redirect to keycloak again
4. My config:
```
{
  "realm": "XXX",
  "auth-server-url": "https://account.gke.XXX.com/auth",
  "ssl-required": "external",
  "resource": "account",
  "verify-token-audience": true,
  "use-resource-role-mappings": true,
  "confidential-port": 0,
  "public-client": true,
  "clientId": "account"
```

**Expected behavior**
Redirects to occur when the access token expires, or when the application developer makes the call.

**Comment by panz3r** [comment]
Hi @mattishii ,

If you are using `check-sso` as the `onLoad` initOption (which is the default) you can notice that a brief redirect to `Keycloak` happens, this is the way in which `keycloak-js` checks for the initial authentication state.
To avoid this you can set the `silentCheckSsoRedirectUri` initOption and setup the silent check page (see the official `keycloak` docs [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter)), this way the SSO check will be done in the background (and no visible redirect will happen).

If you are using `login-required` as the `onLoad` initOption instead, the redirect will happen in case the user is not already logged-in.

Let me know if this helps you.

**Comment by mattishii** [comment]
Thanks a lot!
